load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

package(default_visibility = ["//visibility:public"])

closure_js_library(
    name = "iterables",
    srcs = ["iterables.js"],
    lenient = True,
    deps = ["//closure/goog:base"],
)
